config/routes.rb
Rails.application.routes.draw do

  resources :courses

  resources :schools

  resources :users

  resources :majors

  root 'welcome#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :major
  belongs_to :school
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :school
  belongs_to :major
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def new
  end

  def index
    @courses = Course.all
  end

  def edit
  end

  def show
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(course_params)
    if @course.save
        redirect_to courses_show_path
    end
  end


  private
    def course_params
        params.require(:course).permit(:name, :location, :difficulty, :descrption, :time, :days, :major_id, :school_id)
    end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def new
  end

  def index
  end

  def edit
  end

  def delete
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index

  end


  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to users_path
    else
        render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
end


  def edit
  end

  def delete
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :school_id, :major_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<p>Find me in app/views/courses/edit.html.erb</p>

app/views/courses/index.html.erb
<h3>Here's the course you were looking for</h3>
<p>
  <strong>Title:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>



<h3>Here's a list of the existing courses</h3>

<table>
    <tr>
        <th> Course Name</th>
        <th> Course Location </th>
        <th> Difficulty</th>
        <th> Description</th>
        <th>Time</th>
        <th>Days</th>
        <th>Major</th>
        <th>School</th>
    </tr>

    <% @courses.each do |course| %>
        <tr>
            <td><%= course.name %></td>
            <td><%= course.location %></td>
            <td><%= course.difficulty %></td>
            <td><%= course.description %></td>
            <td><%= course.time %></td>
            <td><%= course.days %></td>
            <td><%= course.major_id %></td>
            <td><%= course.school_id.name %></td>
</table>>

app/views/courses/new.html.erb
<h1>Courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>

app/views/courses/show.html.erb
<h2>This is courses show page </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scheduler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/schools/delete.html.erb
<h1>Schools#delete</h1>
<p>Find me in app/views/schools/delete.html.erb</p>

app/views/schools/edit.html.erb
<h1>Schools#edit</h1>
<p>Find me in app/views/schools/edit.html.erb</p>

app/views/schools/index.html.erb
<h1>Schools#index</h1>
<p>Find me in app/views/schools/index.html.erb</p>

app/views/schools/new.html.erb
<h1>Schools#new</h1>
<p>Find me in app/views/schools/new.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |user| %>
    <p>Name:</p>
    <%= user.text_field :name %>

    <p>E-Mail:</p>
    <%= user.text_field :email %>

    <p>Password:</p>
    <%= user.password_field :password %>

    <p>School:</p>
    <%= user.collection_select :school_id, School.all, :id, :name %>

    <p>Major:</p>
    <%= user.collection_select :major_id, Major.all, :id, :name %>

    <%= user.submit %>

<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Brad's app bitches!</h1>

<h3>Checkout existing courses <%= link_to 'here', courses_index_path %></h3>


<h4>Upload Course Information</h4>
<%= form_for :course, url: courses_path do |course| %>

    <%= course.label :name %>
    <%= course.text_field :name %>
<br>
    <%= course.label :location %>
    <%= course.text_field :location %>
<br>
    <%= course.label :difficulty %>
    <%= course.text_field :difficulty %>
<br>
    <%= course.label :description %>
    <%= course.text_area :description %>
<br>
    <%= course.label :time %>
    <%= course.text_field :time %>
<br>
    <%= course.label :day %>
    <%= course.text_field :day %>

<br>
    <%= course.submit %>

<%end%>